- addons/apecloud-mysql/values.schema.json
RESOLVE https://github.com/apecloud/kubeblocks/issues/5767
> chore: Add `values.schema.json` to `apecloud-mysql`

- README.md
- addons/tidb-cluster/.helmignore
- addons/tidb-cluster/Chart.yaml
- addons/tidb-cluster/templates/_helpers.tpl
- addons/tidb-cluster/templates/cluster.yaml
- addons/tidb-cluster/templates/rbac.yaml
- addons/tidb-cluster/values.yaml
- addons/tidb/.helmignore
- addons/tidb/Chart.yaml
- addons/tidb/templates/_helpers.tpl
- addons/tidb/templates/clusterdefinition.yaml
- addons/tidb/templates/clusterversion.yaml
- addons/tidb/values.yaml
- fix #12 
Support TiDB Cluster Addon with following features (not including TiFlash yet):
> feat: support TiDB cluster

- addons/etcd/templates/clusterdefinition.yaml
fix: https://github.com/apecloud/kubeblocks/issues/5880
> chore: update etcd follower default AccessMode

- addons/redis/scripts/redis-start.sh
refer issue: https://github.com/apecloud/kubeblocks/issues/5874
> chore: redis secondary startup waiting util primary ready

- addons/redis/Chart.yaml
- addons/redis/scripts/redis-sentinel-start.sh
- addons/redis/scripts/redis-start.sh
- addons/redis/templates/clusterdefinition.yaml
refer: https://github.com/apecloud/kubeblocks/issues/5924
> chore: optimize redis default acl and sentinel startup script

- addons/apecloud-mysql/config/mysql8-config-constraint.cue
fix: [[BUG]failed to unmarshal raw OpenAPI schema to JSONSchemaProps](https://github.com/apecloud/kubeblocks/issues/5969)
> fix: failed to transform cue to openapischema (#5969)

- addons/influxdb/.helmignore
- addons/influxdb/Chart.yaml
- addons/influxdb/templates/__helpers.tpl
- addons/influxdb/templates/clusterdefinition.yaml
- addons/influxdb/templates/clusterversion.yaml
- addons/influxdb/values.yaml
> feat: add influxdb addon

- addons/flink-cluster/.helmignore
- addons/flink-cluster/Chart.yaml
- addons/flink-cluster/templates/NOTES.txt
- addons/flink-cluster/templates/_helpers.tpl
- addons/flink-cluster/templates/cluster.yaml
- addons/flink-cluster/templates/validate.yaml
- addons/flink-cluster/values.yaml
- addons/flink/.helmignore
- addons/flink/Chart.yaml
- addons/flink/scripts/setup.sh.tpl
- addons/flink/templates/NOTES.txt
- addons/flink/templates/_helpers.tpl
- addons/flink/templates/clusterdefinition.yaml
- addons/flink/templates/clusterversion.yaml
- addons/flink/templates/configmap.yaml
- addons/flink/values.yaml
- fix https://github.com/apecloud/kubeblocks/issues/6074)
To create a flink cluster (with Job manager, and task manager), 
```bash
1. helm install flink ./addons/flink
2. helm install myflink ./addons/flink-cluster
3.  k port-forward svc/<job-manager-svc-name> 8081
```
and go to "localhost:8081"
you will see
> feat: support flink

- addons/oceanbase-cluster/templates/_helpers.tpl
- addons/oceanbase-cluster/templates/cluster.yaml
- addons/oceanbase-cluster/values.schema.json
- addons/oceanbase-cluster/values.yaml
> chore: add values.schema.json

- addons/oracle/.helmignore
- addons/oracle/dashboards/oracledb.json
- addons/oracle/templates/_helpers.tpl
- addons/oracle/templates/clusterdefinition.yaml
- addons/oracle/templates/clusterversion.yaml
- addons/oracle/templates/monitor/default-asm-metrics.toml
- addons/oracle/templates/monitor/default-metrics.legacy-tablespace.toml
- addons/oracle/templates/monitor/default-metrics.toml
- addons/oracle/values.yaml
- relate to https://github.com/apecloud/apecloud/issues/1064
add oracle monitor pod for oracle
> feat: oracle monitor

- addons/greptimedb/templates/clusterdefinition.yaml
- addons/greptimedb/templates/serviceaccount.yaml
- fix https://github.com/apecloud/kubeblocks/issues/5893
> fix: greptime remove unused SA

- addons/opengauss/Chart.yaml
- addons/opengauss/templates/clusterdefinition.yaml
- fix  https://github.com/apecloud/kubeblocks/issues/6040
> fix: fix opengauss addon in 0.8 KB

- addons/orioledb/config/etcd-serve-config.tpl
- fix https://github.com/apecloud/kubeblocks/issues/6134
> fix: fix orioledb addon

- addons/oceanbase-cluster/templates/_helpers.tpl
- addons/oceanbase-cluster/templates/cluster.yaml
- addons/oceanbase-cluster/values.yaml
- addons/oceanbase/scripts/bootstrap.sh
- addons/oceanbase/templates/componentdefinition.yaml
- subtask  of https://github.com/apecloud/kubeblocks-addons/issues/102
> chore: ob with kb v8 api

- addons/oracle/templates/clusterdefinition.yaml
- fix: https://github.com/apecloud/kubeblocks/issues/6195
> fix: oracle failed in GKE due to permission denied

- addons/apecloud-mysql/values.yaml
New Features in WeScale 0.2.0
- Replace VTConsensus with Lorry
- Support OnlineDDL Pause Command
- Support Branch Command
- Refactor Read-Write-Splitting Code
- Support Intercepting DML without predicates 
- Support Read-Write-Splitting For Read-Only-Transactions
- Support OnlineDDL
- Support TableGC
> chore: upgrade wescale version to 0.2.0

- addons/oceanbase/scripts/bootstrap.sh
- fix [#6289](https://github.com/apecloud/kubeblocks/issues/6289)
> fix: add server with dynamic port

- addons/kafka/scripts/kafka-exporter-setup.sh.tpl
- addons/kafka/scripts/kafka-exporter-setup.tpl
fix https://github.com/apecloud/kubeblocks/issues/6342
> fix: kafka render TLS config error

- .github/workflows/release-chart.yml
1. delete github chart release before upload chart
2. upload all addon parallel
> chore: upload all addon parallel

- addons/influxdb/templates/clusterdefinition.yaml
fix https://github.com/apecloud/kubeblocks/issues/6062
> fix: setup the permission for influxdb volumes

- addons/zookeeper-cluster/values.yaml
- addons/zookeeper/config/zookeeper-config.tpl
- addons/zookeeper/templates/clusterdefinition.yaml
- addons/zookeeper/templates/scripts-configmap.yaml
- addons/zookeeper/values.yaml
1. Update the base image to bitnami
2. Add parameter variables to the parameter template to start the cluster
3. Customize startup script
> fix: Fix zookeeper startup parameter exiting abnormally

- addons/solr-cluster/.helmignore
- addons/solr-cluster/Chart.yaml
- addons/solr-cluster/templates/cluster.yaml
- addons/solr-cluster/values.yaml
- addons/solr/.helmignore
- addons/solr/Chart.yaml
- addons/solr/config/solr-env.tpl
- addons/solr/templates/_helpers.tpl
- addons/solr/templates/clusterdefinition.yaml
- addons/solr/templates/clusterversion.yaml
- addons/solr/templates/config-configmap.yaml
- addons/solr/values.yaml
> feat: support solr addon

- addons/zookeeper-cluster/Chart.yaml
- addons/zookeeper/Chart.yaml
- addons/zookeeper/config/zookeeper-config-constraint.cue
- addons/zookeeper/config/zookeeper-config.tpl
- addons/zookeeper/templates/clusterdefinition.yaml
1、version number changes due to modification of the base image 
2、modified the client port for consistency constraints 
3、delete useless configuration
> refactor: modified specifications and variables

- .github/workflows/release-chart.yml
> chore: auto get addons dir list for release all charts

- addons/apecloud-mysql/Chart.yaml
- addons/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
- addons/apecloud-mysql/config/mysql-scale-vtgate-config-effect-scope.yaml
- addons/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
- addons/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
- addons/apecloud-mysql/scripts/vtgate.sh
- addons/apecloud-mysql/scripts/vttablet.sh
- addons/apecloud-mysql/templates/configconstraint.yaml
- addons/apecloud-mysql/values.yaml
1. Refactor bootstrap script for wescale
2. add 'ddl_strategy' param for wescale VTGate
3. Let wescale use 'autoTrigger' in ConfigConstraint
4. upgrade wescale version from 0.2.3 to 0.2.4
> chore: add params for wescale

- addons/kafka-cluster/templates/_helpers.tpl
- addons/kafka-cluster/templates/cluster.yaml
- addons/kafka-cluster/values.yaml
- addons/kafka/scripts/kafka-exporter-setup.tpl
- addons/kafka/scripts/kafka-server-setup.tpl
- addons/kafka/templates/_helpers_broker_basic.yaml
- addons/kafka/templates/_helpers_combine_basic.yaml
- addons/kafka/templates/_helpers_controller_basic.yaml
- addons/kafka/templates/componentdef-broker-np.yaml
- addons/kafka/templates/componentdef-combine-np.yaml
- addons/kafka/templates/componentdef-combine.yaml
- addons/kafka/templates/componentdef-controller-np.yaml
1. Use ComponentDefinition Apis to build Kafka add-on resources
2. Kafka services support NodePort mode
3. The broker addresses are exposed through the service, and they can be provided with the expose capability later to support public/vpc network access requirements.
> feat: support kafka nodeport in componentDefinition apis

- addons/apecloud-postgresql/templates/clusterdefinition.yaml
- addons/apecloud-postgresql/values.yaml
fix https://github.com/apecloud/kubeblocks/issues/6593
> chore: change syncer image

- addons/mysql/templates/configconstraint.yaml
- fix https://github.com/apecloud/kubeblocks/issues/6600
> chore: update mysql formatterConfig

- addons/apecloud-postgresql/templates/clusterdefinition.yaml
fix: https://github.com/apecloud/kubeblocks/issues/6596
> fix: modify run as user from 999 to 0

- addons/yashandb-cluster/.helmignore
- addons/yashandb-cluster/Chart.yaml
- addons/yashandb-cluster/templates/NOTES.txt
- addons/yashandb-cluster/templates/cluster.yaml
- addons/yashandb-cluster/templates/validate.yaml
- addons/yashandb-cluster/values.schema.json
- addons/yashandb-cluster/values.yaml
- addons/yashandb/configs/install.ini.tpl
- addons/yashandb/scripts/initDB.sh
- addons/yashandb/scripts/install.sh
- addons/yashandb/scripts/startup.sh
- addons/yashandb/scripts/stop.sh
- addons/yashandb/templates/NOTES.txt
- addons/yashandb/templates/_helpers.tpl
- addons/yashandb/templates/clusterdefinition.yaml
- addons/yashandb/templates/configmaps.yaml
- addons/yashandb/templates/scripts.yaml
- addons/yashandb/values.yaml
> chore: add yashan db chart

- addons/kafka-cluster/values.yaml
fix: https://github.com/apecloud/apecloud/issues/2099 & https://github.com/apecloud/apecloud/issues/898
> chore: enable kakfa monitor by default

- addons/apecloud-mysql/Chart.yaml
- addons/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
- addons/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
https://github.com/apecloud/kubeblocks/issues/6661
> fix: set proxy default auth

- addons/apecloud-mysql/Chart.yaml
- addons/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
- addons/apecloud-mysql/config/mysql-scale-vtgate-config-effect-scope.yaml
- addons/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
fix https://github.com/apecloud/apecloud/issues/2487
> fix: add mysql_server_ssl_ca to constraint config

- addons/official-postgresql/templates/clusterdefinition.yaml
fix: https://github.com/apecloud/kubeblocks/issues/6698
> fix: add subpath for offpg

- addons/apecloud-mysql/Chart.yaml
- addons/apecloud-mysql/values.yaml
将wescale从0.2.5升级到了0.2.6，主要改动：
1. 修复日志问题
2. 修复read-after-write失效问题
3. authentication若干优化
4. branch若干小功能增加
5. 非事务DML优化
6. 连接池优化
> upgrade wescale version from 0.2.5 to 0.2.6

- addons/apecloud-mysql/config/mysql8-auditlog-config.tpl
- addons/apecloud-mysql/config/mysql8-config.tpl
- addons/apecloud-mysql/values.yaml
1.change mysql binlog format from **mixed** to **row** to support onlineDDL; 
2.update wescale image tag to 0.2.7
> fix: change mysql binlog format to ROW

- addons/pulsar-cluster/Chart.yaml
- addons/pulsar/Chart.yaml
- addons/pulsar/config/bookies-env.tpl
- addons/pulsar/config/broker-env.tpl
fix ZK reference bug in Pulsar.
> fix: pulsar zookeeper reference error

- addons/postgresql/templates/clusterdefinition.yaml
- addons/postgresql/templates/componentdefinition-12.yaml
- addons/postgresql/templates/componentdefinition-14.yaml
* fix https://github.com/apecloud/kubeblocks/issues/6471
> chore: fix postgresql data directory has invalid permissions

- addons/elasticsearch-cluster/values.schema.json
resolve [kubeclocks/issues/6878](https://github.com/apecloud/kubeblocks/issues/6878)
> chore: add schema.json for es-cluster

- addons/dmdb/.helmignore
- addons/dmdb/Chart.yaml
- addons/dmdb/templates/_helpers.tpl
- addons/dmdb/templates/clusterdefinition.yaml
- addons/dmdb/templates/clusterversion.yaml
- addons/dmdb/values.yaml
> add dmdb addon

- addons/official-postgresql/templates/clusterversion.yaml
fix: https://github.com/apecloud/kubeblocks-addons/issues/431
> fix: delete other default cv for offpg

- addons/apecloud-postgresql/Chart.yaml
- addons/apecloud-postgresql/templates/clusterdefinition.yaml
- addons/apecloud-postgresql/values.yaml
related to: https://github.com/apecloud/kubeblocks-addons/issues/429
> chore: upgrade apecloud postgresql from 14.10 to 14.11

- addons/apecloud-mysql/templates/backuppolicytemplate.yaml
- addons/apecloud-mysql/templates/backuppolicytemplateforhscale.yaml
- addons/apecloud-mysql/templates/componentdefinition.yaml
fix https://github.com/apecloud/kubeblocks/issues/6992
> fix: set backup policy template for the comp-definition of apecloud-mysql

- addons/apecloud-mysql/scripts/setup.sh
fix https://github.com/apecloud/kubeblocks/issues/7254
> fix: apecloud-mysql resolves hostname env error

- addons/minio/values.yaml
fix https://github.com/apecloud/kubeblocks/issues/7222
> fix: minio doesn't specify the default SA

- addons/postgresql/templates/clusterdefinition.yaml
- addons/postgresql/templates/clusterversion.yaml
- addons/postgresql/values.yaml
> chore: set differnt version tags by values

- addons/postgresql/templates/clusterdefinition.yaml
- addons/postgresql/templates/clusterversion.yaml
- addons/postgresql/values.yaml
cherry picked from https://github.com/apecloud/kubeblocks-addons/pull/506
> chore: set differnt version tags by values (#506)

- addons/etcd/templates/clusterdefinition.yaml
- addons/etcd/templates/componentdefinition.yaml
fix https://github.com/apecloud/kubeblocks/issues/7316
> chore: etcd supports non-sequential ordinals

- addons/tidb/templates/clusterdefinition.yaml
Note: this PR targets to release-0.8 branch as in 0.9 tidb addon will use the new API
> chore: adjust tidb component order

- addons/openldap/templates/clusterdefinition.yaml
- addons/weaviate/templates/componentdefinition-weaviate.yaml
- fix https://github.com/apecloud/kubeblocks-addons/issues/524
> fix: remove KB_REPLICA_REPLICS for weaviate and openldap

- addons/mysql/templates/backuppolicytemplate.yaml
- fix https://github.com/apecloud/kubeblocks-addons/issues/532
> chore: add account to mysql bpt

- addons/orchestrator-cluster/.helmignore
- addons/orchestrator-cluster/Chart.yaml
- addons/orchestrator-cluster/templates/NOTES.txt
- addons/orchestrator-cluster/templates/_helpers.tpl
- addons/orchestrator-cluster/templates/cluster.yaml
- addons/orchestrator-cluster/templates/validate.yaml
- addons/orchestrator-cluster/values.schema.json
- addons/orchestrator-cluster/values.yaml
- addons/orchestrator/.helmignore
- addons/orchestrator/Chart.yaml
- addons/orchestrator/configs/orc-backend.cnf
- addons/orchestrator/configs/orc-topology.cnf
- addons/orchestrator/configs/orchestrator.tpl
- addons/orchestrator/scripts/init-meta-database.sh
- addons/orchestrator/scripts/startup.sh
- addons/orchestrator/templates/NOTES.txt
- addons/orchestrator/templates/_helpers.tpl
- addons/orchestrator/templates/clusterdefinition.yaml
- addons/orchestrator/templates/cmpd-raft.yaml
- addons/orchestrator/templates/cmpd-shareend.yaml
- addons/orchestrator/templates/cmpv.yaml
- addons/orchestrator/templates/configmap.yaml
- addons/orchestrator/templates/scripts.yaml
- addons/orchestrator/values.yaml
- picked from https://github.com/apecloud/kubeblocks-addons/pull/567
> fix: add orchestrator

- addons/tidb-cluster/Chart.yaml
- addons/tidb/Chart.yaml
The chart version conflicts with release-0.8
> chore: change tidb chart version to 0.9.0

- addons/mysql/dataprotection/restore.sh
- addons/mysql/templates/actionset-volumesnapshot.yaml
- addons/mysql/templates/actionset-xtrabackup.yaml
- addons/mysql/templates/clusterversion.yaml
- picked from https://github.com/apecloud/kubeblocks-addons/pull/396/files
> chore: set skip slave/replica start if exist signal file (#396)

- addons/apecloud-mysql/values.yaml
- addons/mysql/values.yaml
(cherry picked from commit 097ca63b1fadc57ead2c9589dd5e316e39d8162e)
> fix: updated mysql audit log plugin (#572)

- addons/elasticsearch-cluster/templates/cluster-multi-node.yaml
- addons/elasticsearch-cluster/templates/cluster-single-node.yaml
- addons/elasticsearch/TODO
- addons/elasticsearch/plugins/Dockerfile
- addons/elasticsearch/scripts/install-plugins.sh
- addons/elasticsearch/templates/clusterdefinition.yaml
- addons/elasticsearch/templates/clusterversion.yaml
- addons/elasticsearch/templates/componentdefinition.yaml
- addons/elasticsearch/templates/scripts.yaml
- addons/elasticsearch/values.yaml
…573)
(cherry picked from commit eca4ffbad9d615b2368dd96278a38520cb888436)
> chore[elasticsearch]: support new api

- addons/elasticsearch-cluster/templates/cluster-multi-node.yaml
- addons/elasticsearch-cluster/templates/cluster-single-node.yaml
- addons/elasticsearch-cluster/values.yaml
- addons/elasticsearch/templates/componentdefinition.yaml
- addons/elasticsearch/values.yaml
… list when the cluster is horizontal scaling in
> fix[elasticsearch]: add node to voting configuration exclusions list when the cluster is horizontal scaling in

- addons/kblib-v2/templates/_schedule.tpl
- addons/kblib-v2/values.schema.json
- addons/kblib-v2/values.yaml
- addons/kblib/templates/_schedule.tpl
- addons/kblib/values.schema.json
- addons/kblib/values.yaml
- Support setting affinity node labels in kblib.affinity
Fix: #620
> feat: support setting affinity node labels

- addons/kblib/templates/_schedule.tpl
- addons/kblib/values.schema.json
- addons/kblib/values.yaml
(cherry picked from commit 1d770ce3d1d83ef714feaa714854c160bc29a53c)
> feat: support setting affinity node labels (#621)

- addons/xinference/values.yaml
https://hub.docker.com/r/xprobe/xinference/tags?page=&page_size=&ordering=&name=0.11.0
> chore: change xinference image tag

- addons/milvus/templates/_helpers.tpl
- addons/oceanbase-ce/templates/clusterversion.yaml
- addons/oceanbase-ce/templates/componentdefinition.yaml
Replace `{{ default .Values.images.pullPolicy "IfNotPresent" }}` to `{{ default "IfNotPresent" .Values.images.pullPolicy }}`
https://helm.sh/docs/chart_template_guide/function_list/#default
> chore: fix default imagePullPolicy functions

- addons/apecloud-mysql-cluster/values.schema.json
- addons/camellia-redis-proxy-cluster/values.schema.json
- addons/kblib/templates/_storages.tpl
- addons/minio-cluster/values.schema.json
- addons/mogdb-cluster/values.schema.json
- addons/mongodb-cluster/values.schema.json
- addons/official-postgresql-cluster/values.schema.json
- addons/opengauss-cluster/values.schema.json
- addons/oracle-cluster/values.schema.json
- addons/oracle-mysql-cluster/values.schema.json
- addons/orioledb-cluster/values.schema.json
- addons/postgresql-cluster/values.schema.json
- addons/qdrant-cluster/values.schema.json
- addons/redis-cluster/values.schema.json
- addons/tdengine-cluster/values.schema.json
(cherry picked from commit 8eb6feab0f21a860062a7080be8ce64a6f76a809)
> feat: support set storage class for clusters (#458)

- addons-cluster/apecloud-mysql-cluster/templates/_helpers.tpl
- addons-cluster/apecloud-mysql-cluster/templates/cluster.yaml
- addons/apecloud-mysql/scripts/vtgate.sh
- addons/apecloud-mysql/scripts/vttablet.sh
- addons/apecloud-mysql/templates/_helpers.tpl
- addons/apecloud-mysql/templates/clusterdefinition.yaml
- addons/apecloud-mysql/templates/cmpd-apecloudmysql.yaml
- addons/apecloud-mysql/templates/cmpd-proxy.yaml
- addons/apecloud-mysql/templates/cmpdversion.yaml
- addons/apecloud-mysql/values.yaml
This reverts commit 57f41fd7fbdd3808588646d0713b3e4b2bfdef6f.
> chore: revert-apecloud-mysql-remove-wescale

- addons/apecloud-mysql/scripts/vttablet.sh
ref: https://github.com/apecloud/kubeblocks-addons/pull/659
> chore: set db_host to 127.0.0.1

- addons/influxdb/templates/cmpd.yaml
- addons/influxdb/values.yaml
https://github.com/apecloud/kubeblocks-addons/issues/690
> fix influxes addon hardcode value

- addons/nebula/templates/cmpv.yaml
- addons/nebula/values.yaml
https://github.com/apecloud/kubeblocks-addons/issues/684
> fix nubula addon hardcode image

- addons/greptimedb/templates/cmpv.yaml
- addons/greptimedb/values.yaml
https://github.com/apecloud/kubeblocks-addons/issues/681
> fix greptimedb hardcode image

- addons/apecloud-mysql/values.yaml
- addons/apecloud-postgresql/values.yaml
- addons/camellia-redis-proxy/values.yaml
- addons/kafka/values.yaml
- addons/llm/templates/clusterversion.yaml
- addons/llm/values.yaml
- addons/mogdb/templates/swithover.yaml
- addons/mongodb/templates/componentversion-mongodb.yaml
- addons/mongodb/values.yaml
- addons/mysql/templates/_helpers.tpl
- addons/mysql/templates/componentdefinition-mysql-8.0-orc.yaml
- addons/mysql/templates/componentdefinition-mysql-8.0.yaml
- addons/mysql/values.yaml
- addons/opengauss/values.yaml
- addons/orchestrator/values.yaml
- addons/orioledb/values.yaml
- addons/postgresql/templates/componentversion.yaml
- addons/postgresql/values.yaml
- addons/pulsar/values.yaml
- addons/redis/templates/componentversion-redis-cluster.yaml
- addons/redis/templates/componentversion-redis-sentinel.yaml
- addons/redis/templates/componentversion-redis.yaml
- addons/redis/values.yaml
- addons/tdengine/values.yaml
- addons/xinference/values.yaml
- examples/neon/cluster.yaml
> chore: switch aliyun image registry infracreate to apecloud

- addons/mogdb/templates/clusterdefinition.yaml
- fix https://github.com/apecloud/kubeblocks/issues/7496
> fix: offline instance causes crash

- addons/mogdb/templates/clusterdefinition.yaml
- fix https://github.com/apecloud/kubeblocks/issues/7674
> fix: mogdb hscale crash

- addons-cluster/oceanbase-ce-cluster/values.schema.json
- addons/oceanbase-ce/scripts/entrypoint.sh
- addons/oceanbase-ce/templates/componentdefinition.yaml
- pick from https://github.com/apecloud/kubeblocks-addons/pull/751
> chore: update ob service version

- examples/apecloud-mysql/expose-disable.yaml
- examples/apecloud-mysql/expose-enable.yaml
- examples/apecloud-postgresql/expose-disable.yaml
- examples/apecloud-postgresql/expose-enable.yaml
- examples/camellia-redis-proxy/expose-disable.yaml
- examples/camellia-redis-proxy/expose-enable.yaml
- examples/mogdb/cluster.yaml
- examples/mogdb/expose-disable.yaml
- examples/mogdb/expose-enable.yaml
- examples/mogdb/verticalscale.yaml
- examples/mongodb/expose-disable.yaml
- examples/mongodb/expose-enable.yaml
- examples/mysql/expose-disable.yaml
- examples/mysql/expose-enable.yaml
- examples/oceanbase/expose-disable.yaml
- examples/oceanbase/expose-enable.yaml
- examples/orioledb/expose-disable.yaml
- examples/orioledb/expose-enable.yaml
- examples/postgresql/expose-disable.yaml
- examples/postgresql/expose-enable.yaml
- examples/redis/expose-disable.yaml
- examples/redis/expose-enable.yaml
resolve https://github.com/apecloud/kubeblocks-addons/issues/763
> feat: example expose roleSelector specified

- addons/postgresql/scripts/pgbouncer_setup.sh
pgbouncer configuration document: https://www.pgbouncer.org/config.html#section-databases
> chore: support all client db connect to pgbouncer by default

- examples/orchestrator/README.md
- examples/orchestrator/cluster-raft.yaml
- examples/orchestrator/cluster-shareend.yaml
- examples/orchestrator/horizontalscale.yaml
- examples/orchestrator/restart.yaml
- examples/orchestrator/start.yaml
- examples/orchestrator/stop.yaml
- examples/orchestrator/verticalscale.yaml
- examples/orchestrator/volumeexpand.yaml
resolve https://github.com/apecloud/kubeblocks-addons/issues/798
> feat: add orchestrator example

- .github/utils/utils.sh
- .github/workflows/shellcheck-push.yml
- Makefile
resolve https://github.com/apecloud/kubeblocks-addons/issues/786
1. add shell check for push
2. only check increment files
3. add `make shellcheck` on all shell scripts locally
> chore: add shell check workflow

- addons-cluster/victoria-metrics-cluster/templates/_helpers.tpl
- addons/victoria-metrics/Chart.yaml
- addons/victoria-metrics/templates/cmpd-vmselect.yaml
- addons/victoria-metrics/templates/cmpv.yaml
- addons/victoria-metrics/values.yaml
Including Registry,ServiceName,ClusterName..
> Chore/correct some settings for VictoriaMetrics

- addons/zookeeper/config/zookeeper-config.tpl
- addons/zookeeper/dataprotection/backup.sh
- addons/zookeeper/dataprotection/restore.sh
- addons/zookeeper/templates/backupactionset.yaml
- addons/zookeeper/templates/backuppolicytemplate.yaml
- addons/zookeeper/templates/cmpd.yaml
- addons/zookeeper/values.yaml
fix https://github.com/apecloud/apecloud/issues/5084
> feature: add backup for zookeeper

- .github/workflows/shellcheck-push.yml
fix delete file not exist
https://github.com/apecloud/kubeblocks-addons/actions/runs/10106296735/job/27948166499
> chore: fix file does not exist

- addons/zookeeper/templates/backuppolicytemplate.yaml
fix https://github.com/apecloud/apecloud/issues/5863
> fix: missing cd ref in zookeeper backup template

- addons/mogdb/scripts/helper.sh
- addons/mogdb/templates/clusterdefinition.yaml
> chore: use set -e instead of -ex

- addons/orchestrator/templates/cmpd-raft.yaml
- addons/zookeeper/config/log4j.properties
- addons/zookeeper/templates/cmpd.yaml
- addons/zookeeper/templates/cmpv.yaml
- addons/zookeeper/templates/comfigmap.yaml
> chore: support zookeeper ver 3.6

- addons-cluster/apecloud-mysql/templates/cluster.yaml
- addons-cluster/mysql/templates/cluster.yaml
- addons/mysql/templates/_helpers.tpl
- addons/mysql/templates/backuppolicytemplate.yaml
- addons/mysql/templates/backuppolicytemplateforhscale.yaml
- addons/mysql/templates/cmpd-mysql57-orc.yaml
- addons/mysql/templates/cmpd-mysql80-orc.yaml
- addons/mysql/templates/switchover.yaml
- addons/mysql/values.yaml
> feature: add exporter for mysql addon

- addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
This PR fixes the issue https://github.com/apecloud/kubeblocks-addons/issues/906.
> fix: Retry joining cluster to make sure DNS refreshed (#906)

- addons/redis/redis-cluster-scripts/redis-cluster-manage.sh
- addons/redis/redis-cluster-scripts/redis-cluster-replica-member-leave.sh
- addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
- addons/redis/scripts/redis-preStop.sh
(cherry picked from commit 444d8c398d11009cbc7d3c35a7e6c001d7eeac43)
> chore: modify redis xtrace empty password logic 

- addons/elasticsearch/scripts/prepare-fs.sh
- addons/elasticsearch/scripts/suspend.sh
- addons/elasticsearch/templates/componentdefinition.yaml
- addons/elasticsearch/templates/componentversion.yaml
- addons/elasticsearch/templates/scripts.yaml
(cherry picked from commit e7d0c1836bf597654aa5199d68a1a408a89561c9)
> chore[elasticsearch]: tidy up init containers (#956)

- addons/elasticsearch/templates/componentdefinition.yaml
(cherry picked from commit b9c337fc4e7442af07475f025ee13db7099b639d)
> chore[elasticserach]: delete the voting config exclusion list (#963)

- addons-cluster/zookeeper-cluster/templates/cluster.yaml
- addons-cluster/zookeeper-cluster/values.yaml
- addons/zookeeper/config/logback.xml
- addons/zookeeper/config/zookeeper-config.tpl
- addons/zookeeper/scripts/startup.sh
- addons/zookeeper/templates/cmpd.yaml
- addons/zookeeper/templates/cmpv.yaml
- addons/zookeeper/templates/scripts.yaml
(cherry picked from commit 21b112ef41cff4c860b561a8b9df1a008c24eb09)
> chore: zookeeper support version 3.4 (#955)

- addons/mogdb/templates/cmpd.yaml
- fix https://github.com/apecloud/kubeblocks/issues/7930
> chore: update mogdb roleProbe

- addons-cluster/mysql/values.schema.json
- addons/mysql/config/mysql8.0-config.tpl
- addons/mysql/templates/backuppolicytemplate.yaml
- addons/mysql/templates/cmpd-mysql80.yaml
- addons/mysql/templates/cmpd-mysql84.yaml
- addons/mysql/values.yaml
- fix https://github.com/apecloud/kubeblocks/issues/7994
> feat: support mysql 8.4

- addons/etcd/templates/clusterdefinition.yaml
- to https://github.com/apecloud/kubeblocks/issues/8130
> chore: add consensus spec for etcd

- .github/workflows/check-chart-push.yml
- hack/update-readme.sh
resolve https://github.com/apecloud/kubeblocks-addons/issues/1033
> chore: add auto update readme workflow

- examples/mysql/switchover-specified-instance.yaml
- examples/mysql/switchover.yaml
- fix https://github.com/apecloud/kubeblocks-addons/issues/1042
> chore: update mysql switchover using custom-ops

- addons/redis/config/redis7-config-constraint.cue
- addons/redis/config/redis7-config-effect-scope.yaml
- addons/redis/dataprotection/common-scripts.sh
- addons/redis/dataprotection/pitr-backup.sh
- addons/redis/dataprotection/pitr-restore.sh
- addons/redis/templates/backupactionset.yaml
- addons/redis/templates/backuppolicytemplate.yaml
Cherry-pick [release-0.9/[feat: support redis(standalone replica) pitr]](https://github.com/apecloud/kubeblocks-addons/pull/961)
> feat: support redis(standalone replica) pitr

- README.md
- addons/mysql/config/mysql8-config-constraint.cue
* fix: https://github.com/apecloud/apecloud/issues/6714
> fix: delete duplicated mysql cue parameter values

- addons-cluster/elasticsearch/templates/_helpers.tpl
(cherry picked from commit f2c7201c75d8313b82eb7bfa66ae72a26d34652c)
> fix: error calling semver, invalid semantic version (#1058)

- addons/redis/dataprotection/pitr-restore.sh
- addons/redis/dataprotection/restore-keys.sh
- addons/redis/dataprotection/switch-data-dir.sh
- addons/redis/templates/backupactionset.yaml
cherry-pick release-0.9/[#1023](https://github.com/apecloud/kubeblocks-addons/pull/1023)
Resolve https://github.com/apecloud/kubeblocks/issues/8128
> feat: redis-restore-by-keys

- addons/polardbx/Chart.yaml
- addons/polardbx/templates/clusterDefintion.yaml
- fix https://github.com/apecloud/kubeblocks/issues/8242
> chore: polardb updates workloadType from Consensus to Stateful

- addons-cluster/orchestrator-cluster/templates/cluster.yaml
- addons-cluster/orchestrator-cluster/values.yaml
- addons/orchestrator/.helmignore
- addons/orchestrator/configs/orchestrator.tpl
- addons/orchestrator/orchestrator/Dockerfile
- addons/orchestrator/scripts/init-meta-database.sh
- addons/orchestrator/scripts/startup.sh
- addons/orchestrator/templates/_helpers.tpl
- addons/orchestrator/templates/cmpd-raft.yaml
- addons/orchestrator/templates/cmpd-shareend.yaml
- addons/orchestrator/values.yaml
cherry pick https://github.com/apecloud/kubeblocks-addons/pull/789
> chore: fix create orchestrator

- addons/kblib/templates/_liblogs.tpl
- addons/postgresql/dataprotection/wal-g-backup.sh
- addons/postgresql/dataprotection/wal-g-config.sh
- addons/postgresql/dataprotection/wal-g-delete.sh
- addons/postgresql/dataprotection/wal-g-restore.sh
- addons/postgresql/scripts/postgres-pre-setup.sh
- addons/postgresql/scripts/wal-g-wal-archive.sh
- addons/postgresql/scripts/wal-g-wal-restore.sh
- addons/postgresql/templates/actionset-wal-g.yaml
- addons/postgresql/templates/scripts.yaml
- Add the logging capability for PostgreSQL WAL-G scripts
- Created wrapper scripts for WAL-G WAL archive/restore, adding the logs into the files, so that we can retrieve the history
- Fixed shellcheck errors
Fix: #1119
> feat: logging for PostgreSQL wal-g scripts

- addons-cluster/clickhouse-cluster/Chart.yaml
- addons-cluster/clickhouse-cluster/templates/NOTES.txt
- addons-cluster/clickhouse-cluster/templates/_helpers.tpl
- addons-cluster/clickhouse-cluster/templates/cluster-tls-secrets.yaml
- addons-cluster/clickhouse-cluster/values.yaml
- addons/clickhouse/Chart.yaml
- addons/clickhouse/configs/00_default_overrides.xml.tpl
- addons/clickhouse/configs/ch-keeper_00_default_overrides.xml.tpl
- addons/clickhouse/configs/client.xml.tpl
- addons/clickhouse/configs/user.xml.tpl
- addons/clickhouse/templates/cmpd-ch.yaml
- addons/clickhouse/templates/cmpd-keeper.yaml
- addons/clickhouse/templates/cmpv.yaml
- addons/clickhouse/templates/configmap.yaml
- addons/clickhouse/values.yaml
- examples/clickhouse/cluster-single-node.yaml
- examples/clickhouse/cluster.yaml
pick tls to 0.9 and resolve [#8315](https://github.com/apecloud/kubeblocks/issues/8316)
> pick tls clickhouse to 0.9 and fix authentication failed

- addons-cluster/influxdb/.helmignore
- addons-cluster/influxdb/Chart.yaml
- addons-cluster/influxdb/templates/NOTES.txt
- addons-cluster/influxdb/templates/_helpers.tpl
- addons-cluster/influxdb/templates/cluster.yaml
- addons-cluster/influxdb/values.schema.json
- addons-cluster/influxdb/values.yaml
- fix https://github.com/apecloud/kubeblocks-addons/issues/1156
> chore: add influxdb cluster chart

- addons/kafka/scripts/kafka-server-setup.tpl
> support:kafka broker pod direct access[0.9]

- addons-cluster/zookeeper/templates/cluster.yaml
- addons-cluster/zookeeper/values.yaml
> fix: zookeeper default terminationPolicy

- addons-cluster/kafka-cluster/templates/_helpers.tpl
- addons-cluster/kafka-cluster/templates/cluster.yaml
- addons-cluster/kafka-cluster/values.yaml
- add kafka-exporter resource control by helm values
- add podIp control by nodeportEnable param
> fix: kafka exporter resource manage

- addons-cluster/kafka-cluster/templates/cluster.yaml
support podip in separated mode
> fix: [kafka] support podip in separated mode

- examples/postgresql/README.md
- examples/postgresql/cluster.yaml
- examples/postgresql/pod-monitor.yml
> chore: add observibility

- addons/clickhouse/templates/cmpd-ch.yaml
- addons/clickhouse/templates/cmpd-keeper.yaml
fixed clickhouse metrics on cloud[#7399](https://github.com/apecloud/apecloud/issues/7399)
> chore: fix metrics env

- addons/neon/templates/_helpers.tpl
- addons/neon/templates/cmpv-compute.yaml
- addons/neon/templates/cmpv-pageserver.yaml
- addons/neon/templates/cmpv-safekeeper.yaml
- addons/neon/templates/cmpv-storagebroker.yaml
- fix https://github.com/apecloud/kubeblocks/issues/8458
> chore: update neon image using tpl

- addons-cluster/mariadb/templates/cluster.yaml
- fix https://github.com/apecloud/kubeblocks/issues/8471
> chore: update mariadb cluster with storage and ns

- addons-cluster/mysql/templates/cluster.yaml
- addons/orchestrator/templates/cmpd-raft.yaml
- fix https://github.com/apecloud/kubeblocks-addons/issues/1221
> fix: update orc role probe scripts

- addons/zookeeper/scripts-ut-spec/roleprobe_spec.sh
- addons/zookeeper/scripts-ut-spec/startup_spec.sh
- addons/zookeeper/scripts/roleprobe.sh
- addons/zookeeper/scripts/startup.sh
- addons/zookeeper/values.yaml
fix https://github.com/apecloud/kubeblocks/issues/8470
> chore: update scripts for zookeeper

- addons-cluster/apecloud-postgresql-cluster/templates/cluster.yaml
- addons/apecloud-postgresql/templates/cmpd-apepg.yaml
- addons/apecloud-postgresql/values.yaml
* fix: https://github.com/apecloud/kubeblocks/issues/8487
> fix: apepg svc connect error

- .github/CODEOWNERS
- addons/mysql/templates/_helpers.tpl
> fix: mysql orc roleprobe error

- addons/etcd/scripts-ut-spec/member_leave_spec.sh
- addons/etcd/scripts/member-join.sh
- addons/etcd/scripts/member-leave.sh
- addons/etcd/templates/cmpd.yaml
resolve https://github.com/apecloud/kubeblocks/issues/8555
> fix: etcd member join and leave

- addons/tidb/templates/actionset.yaml
- addons/tidb/templates/backuppolicytemplate.yaml
- addons/tidb/templates/clusterdefinition.yaml
- addons/tidb/templates/componentdefinition-pd-8.yaml
- addons/tidb/templates/componentdefinition-tidb-8.yaml
- addons/tidb/templates/componentdefinition-tikv-8.yaml
- addons/tidb/templates/componentversion.yaml
- addons/tidb/values.yaml
follow up of https://github.com/apecloud/kubeblocks-addons/pull/1226
TODO: port to main
> chore: support tidb 8.4

- addons/zookeeper/dataprotection/backup.sh
- addons/zookeeper/dataprotection/restore.sh
- addons/zookeeper/templates/backupactionset.yaml
> fix: zookeeper backup size incorrect 

- addons/mogdb/templates/cmpd.yaml
- addons/mogdb/templates/cmpv.yaml
- fix: https://github.com/apecloud/kubeblocks/issues/8610
> chore: update mogdb rolepProbe with image

- addons/opensearch/templates/cmpd-dashboard.yaml
- fix https://github.com/apecloud/kubeblocks/issues/8653
> bugfix: opensearch update OPENSEARCH_HOSTS

- addons/orchestrator/templates/cmpd-raft.yaml
- addons/orchestrator/templates/cmpd-shareend.yaml
> fix: orc addon missing COMPONENT_NAME var

- addons/mysql/scripts/init-mysql-instance-for-orc.sh
- addons/mysql/scripts/mysql-entrypoint.sh
- addons/mysql/scripts/mysql-orchestrator-register.sh
- addons/mysql/templates/_helpers.tpl
1. check mysql major version
2. use cluster component name instead of short name
resolves #1352
> fix: mysql addon error on mysql 5.7 with orc

- examples/mongodb/cluster.yaml
- fix: https://github.com/apecloud/kubeblocks-addons/issues/1361
> chore: udpate mongodb cluster create example

- addons/oceanbase-ce/templates/_helpers.tpl
- fix https://github.com/apecloud/kubeblocks/issues/8710
> chore: update ob cmpd MANAGER_PORT vars

- addons/zookeeper/dataprotection/restore.sh
> fix: zookeeper restore fail

- addons/clickhouse/configs/00_default_overrides.xml.tpl
- addons/clickhouse/templates/cmpd-clickhouse.yaml
> chore: fix clickhouse sharding bootstrap

- examples/clickhouse/README.md
- examples/clickhouse/reconfig.yaml
-  fix https://github.com/apecloud/kubeblocks-addons/issues/1398
> chore: add reconfig for clickhouse

- addons/redis/redis-cluster-scripts/redis-cluster-common.sh
- addons/redis/redis-cluster-scripts/redis-cluster-switchover.sh
- addons/redis/scripts-ut-spec/redis_switchover_spec.sh
- addons/redis/scripts/redis-switchover.sh
- addons/redis/templates/cmpd-redis-cluster-7.yaml
(cherry picked from commit c211bec2b94806081e8ac6d8daba6efcc2e1e8fa)
> chore: support redis cluster switchover and optimize sentinel switchover

- addons/mysql/templates/cpmv-proxysql.yaml
fix https://github.com/apecloud/kubeblocks/issues/8830
> chore: fix mysql proxysql cmpv status Unavailable

- examples/docs/enable-kubeblocks-metrics.md
- examples/docs/kubeblocks-dashboard.json
add steps hwo to enable runtime metrics for KubeBlocks.
- as impl. in  https://github.com/apecloud/kubeblocks/issues/6611
> chore: enable kb metrics feature gate

- examples/docs/kubeblocks-dashboard.json
set datasource as dastasource vars.
> chore: update kb dashboard with datasource as vars

- addons-cluster/clickhouse/values.yaml
- addons-cluster/greptimedb/values.schema.json
- addons-cluster/kblib/values.schema.json
- addons-cluster/orioledb/values.yaml
- addons-cluster/postgresql/values.yaml
- addons-cluster/pulsar/values.yaml
- addons-cluster/risingwave/values.yaml
- addons-cluster/tidb/values.yaml
- addons-cluster/victoria-metrics/values.schema.json
- fix https://github.com/apecloud/kubeblocks/issues/8909
> chore: remove HATL

- addons-cluster/mysql/values.schema.json
- fix https://github.com/apecloud/kubeblocks/issues/8920
> fix: update mysql default topology value

- addons/mysql/scripts/init-mysql-instance-for-orc.sh
- addons/mysql/scripts/mysql-entrypoint.sh
- addons/mysql/scripts/mysql-orchestrator-register.sh
fix https://github.com/apecloud/kubeblocks/issues/8938
> fix: check length of master host for mysql5

- addons/apecloud-postgresql/templates/_helpers.tpl
- addons/apecloud-postgresql/templates/cmpv.yaml
* fix https://github.com/apecloud/kubeblocks/issues/8966
> fix: apepg accountProvision

- addons/kafka/templates/cmpd-broker-27.yaml
- addons/kafka/templates/cmpd-broker.yaml
- addons/kafka/templates/cmpd-combine.yaml
- addons/kafka/templates/cmpd-controller.yaml
- addons/kafka/values.yaml
> feat: support custom volumeMount and envs

- addons-cluster/zookeeper-cluster/templates/cluster.yaml
- addons/zookeeper/scripts/startup.sh
- addons/zookeeper/templates/backuppolicytemplate.yaml
- addons/zookeeper/templates/cmpd-deprecated.yaml
- addons/zookeeper/templates/cmpd.yaml
- addons/zookeeper/templates/cmpv.yaml
* resolve: https://github.com/apecloud/apecloud/issues/10115
> feat: zookeeper new cmpd

- .github/workflows/cherry-pick.yml
fix https://github.com/apecloud/kubeblocks-addons/actions/runs/13784367242/job/38549020602
> chore: fix comment actions error

- addons/etcd/config/etcd.conf.yaml.tpl
- addons/etcd/scripts-ut-spec/common_spec.sh
- addons/etcd/scripts/common.sh
- examples/docs/install-plg-stack.md
- examples/etcd/README.md
- examples/etcd/cluster-with-tls.yaml
- fix  https://github.com/apecloud/kubeblocks/issues/9054
> fix: update etcd config and roleProbe

- addons/kafka/templates/cmpd-broker-27.yaml
- addons/kafka/templates/cmpd-broker.yaml
- addons/kafka/templates/cmpd-combine.yaml
- addons/kafka/templates/cmpd-controller.yaml
- addons/kafka/values.yaml
- addons/zookeeper/templates/cmpd.yaml
> kafka's jmx-exporter support custom envs and port

- addons/apecloud-mysql/dataprotection/backup.sh
- addons/apecloud-mysql/dataprotection/xtrabackup-incremental-backup.sh
- addons/apecloud-mysql/dataprotection/xtrabackup-incremental-restore.sh
- addons/mysql/dataprotection/backup.sh
- addons/mysql/dataprotection/xtrabackup-incremental-backup.sh
- addons/mysql/dataprotection/xtrabackup-incremental-restore.sh
ref https://github.com/apecloud/kubeblocks/pull/9042
> fix: align target instance of mysql inc backup

- addons/postgresql/templates/backuppolicytemplate.yaml
fix https://github.com/apecloud/kubeblocks/issues/9093
> chore: fix pg 15 16 missing backuppolicy

- addons/redis/redis-cluster-scripts/redis-cluster-common.sh
- addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
- addons/redis/scripts-ut-spec/redis_cluster_server_start_spec.sh
fix issue: https://github.com/apecloud/kubeblocks/issues/9083
> chore: redis cluster stop-start re-meet all nodes

- addons/pulsar/config/2.11.2/bookies-config.tpl
- addons/pulsar/config/3.0.2/bookies-config.tpl
- addons/pulsar/config/pulsar-env-optimize.tpl
- addons/pulsar/config/pulsar-env.tpl
- addons/pulsar/templates/cmpd-bookies-recovery-2.yaml
- addons/pulsar/templates/cmpd-bookies-recovery-3.yaml
- addons/pulsar/templates/cmpd-bookkeeper-2.yaml
- addons/pulsar/templates/cmpd-bookkeeper-3.yaml
- addons/pulsar/templates/cmpd-broker-2.yaml
- addons/pulsar/templates/cmpd-broker-3.yaml
- addons/pulsar/templates/cmpd-proxy-2.yaml
- addons/pulsar/templates/cmpd-proxy-3.yaml
- addons/pulsar/templates/cmpd-zookeeper-2.yaml
- addons/pulsar/templates/cmpd-zookeeper-3.yaml
- fix: https://github.com/apecloud/kubeblocks/issues/9237
> chore: update tpl for opensearch and pulsar

- addons/pulsar/README.md
- addons/pulsar/templates/_helpers.tpl
- addons/pulsar/templates/config/paramsdef-broker-2.yaml
- addons/pulsar/templates/config/paramsdef-broker-3.yaml
- examples/pulsar/README.md
- examples/pulsar/reconfigure-broker.yaml
- to : https://github.com/apecloud/kubeblocks/issues/9247
> chore: update pulsar tools image

- .github/workflows/shellspec-push.yml
> chore: upgrade runs version ubuntu-latest

- addons/pulsar/README.md
- addons/pulsar/templates/_helpers.tpl
- addons/pulsar/templates/config/paramsdef-broker-2.yaml
- addons/pulsar/templates/config/paramsdef-broker-3.yaml
- examples/pulsar/README.md
- examples/pulsar/reconfigure-broker.yaml
> chore: update pulsar tools image (#1601)

- addons/redis/redis-cluster-scripts/redis-cluster-manage.sh
- addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
- addons/redis/scripts/redis-register-to-sentinel.sh
- addons/redis/scripts/redis-sentinel-start-v2.sh
- addons/redis/scripts/redis-start.sh
- addons/redis/templates/componentdefinition-redis-cluster.yaml
- addons/redis/templates/componentdefinition-redis-sentinel.yaml
- addons/redis/templates/componentdefinition-redis.yaml
refer issue: https://github.com/apecloud/kubeblocks/issues/9172
> chore: refine redis host network vars

- addons-cluster/elasticsearch/templates/_validate.yaml
- addons-cluster/elasticsearch/templates/cluster-multi-node.yaml
- addons-cluster/elasticsearch/templates/cluster-single-node.yaml
- addons-cluster/elasticsearch/values.yaml
- addons/elasticsearch/README.md
- addons/elasticsearch/configs/elasticsearch-7-log4j2.properties
- addons/elasticsearch/configs/elasticsearch-7.yml.tpl
- addons/elasticsearch/configs/elasticsearch-8.yml.tpl
- addons/elasticsearch/templates/cmpd-7.yaml
- addons/elasticsearch/templates/cmpd-8.yaml
- examples/elasticsearch/README.md
- examples/elasticsearch/cluster-multi-node-708.yaml
- examples/elasticsearch/cluster-single-node-with-sp.yaml
- examples/elasticsearch/cluster-single-node.yaml
(cherry picked from commit dd89bcafa17d28a5e844c9d48571a43754cb34ed)
> chore: update es tpl and examples (#1613)

- addons/mysql/config/proxysql.tpl
- addons/mysql/scripts/configure-proxysql.sh
- addons/mysql/scripts/proxysql-entry.sh
- addons/mysql/templates/cmpd-proxysql.yaml
- fix https://github.com/apecloud/kubeblocks-addons/issues/1616
- fix https://github.com/apecloud/kubeblocks/issues/9194
> chore: update mysql proxy tpl

- addons/mysql/templates/backuppolicytemplate.yaml
- fix  https://github.com/apecloud/kubeblocks/issues/9270
> chore: update mysql bpt with cmpd mysql-orc

- addons/postgresql/README.md
- addons/postgresql/scripts/switchover.sh
- addons/postgresql/templates/cmpd-12.yaml
- addons/postgresql/templates/cmpd-14.yaml
- addons/postgresql/templates/cmpd-15.yaml
- addons/postgresql/templates/cmpd-16.yaml
- examples/postgresql/rebuild.yaml
- examples/postgresql/switchover-specified-instance.yaml
- examples/postgresql/switchover.yaml
changes are:
1.  fetch PRIMARY info from patroni
2.  remove env POSTGRESQL_PRIMARY_POD_NAME from cmpd
3. send swithover request to 127.0.0.1:8080 port.
> chore: update pg switchover action

- addons/apecloud-mysql/templates/_helpers.tpl
- addons/apecloud-postgresql/templates/_helpers.tpl
- addons/etcd/scripts/switchover.sh
- addons/mongodb/templates/cmpd.yaml
- addons/postgresql/scripts-ut-spec/switchover_spec.sh
- addons/postgresql/scripts/switchover.sh
- addons/tidb/scripts/pd_switchover.sh
- addons/tidb/scripts/tikv_member_leave.sh
- addons/tidb/templates/cmpd-pd.yaml
- addons/tidb/templates/cmpv.yaml
- addons/vanilla-postgresql/scripts/switchover.sh
manually pick https://github.com/apecloud/kubeblocks-addons/pull/1338
> chore: support new switchover action (#1338)

- addons/mongodb/dataprotection/mongo-pitr-restore.sh
- addons/postgresql/dataprotection/wal-g-backup.sh
- addons/postgresql/dataprotection/wal-g-incremental-backup.sh
- addons/postgresql/templates/cmpd-12.yaml
- addons/postgresql/templates/cmpd-14.yaml
- addons/postgresql/templates/cmpd-15.yaml
- addons/postgresql/templates/cmpd-16.yaml
- fix https://github.com/apecloud/kubeblocks/issues/9333
> chore: use vars defined in cmpd to replace KB_ envs

- addons/kafka/templates/config-template.yaml
> chore: kfk2's config template should be helm resource policy keep

- .github/CODEOWNERS
- README.md
- addons/kafka/templates/cmpd-broker-27.yaml
- addons/kafka/templates/cmpd-broker.yaml
- addons/kafka/templates/cmpd-combine.yaml
- addons/kafka/templates/cmpd-controller.yaml
> feat: kfk's jmx-exporter support hot reload

- .github/CODEOWNERS
- .github/workflows/check-chart-push.yml
- README.md
- addons/etcd/Chart.yaml
install yq specify version 4.44.3
> chore: install yq

- addons/redis/scripts-ut-spec/redis_sentinel_member_leave_spec.sh
fix https://github.com/apecloud/kubeblocks-addons/actions/runs/15080044361/job/42395131783
> chore: fix shellspec test error

- addons/orioledb/config/pg16-config.tpl
- addons/postgresql/config/pg12-config.tpl
- addons/postgresql/config/pg14-config.tpl
- addons/postgresql/config/pg15-config.tpl
- addons/postgresql/config/pg16-config.tpl
- addons/vanilla-postgresql/config/pg12-config.tpl
- addons/vanilla-postgresql/config/pg14-config.tpl
- addons/vanilla-postgresql/config/pg15-config.tpl
Reverts apecloud/kubeblocks-addons#1679
> Revert "chore: set pg max_worker_processes to 8"

- addons/postgresql/scripts-ut-spec/postgres_setup_spec.sh
fix https://github.com/apecloud/kubeblocks-addons/actions/runs/15315812026/job/43089354686
> chore: fix shell spec test

- addons/kafka/values.yaml
> chore: change kafka-exporter repository

- addons/etcd/templates/_helpers.tpl
- addons/etcd/templates/cmpd.yaml
- addons/etcd/values.yaml
resolve https://github.com/apecloud/apecloud/issues/12158
> fix: etcd09 busybox image

- addons/nebula/templates/cmpd-console.yaml
- addons/nebula/templates/cmpd-graphd.yaml
- addons/nebula/templates/cmpd-metad.yaml
- addons/nebula/templates/cmpd-storaged.yaml
- addons/nebula/templates/cmpv.yaml
- addons/nebula/values.yaml
fix https://github.com/apecloud/apecloud/issues/12242
> chore: refine nebula images values

- addons-cluster/redis/templates/prometheus/server-monitor.yaml
add redis metric server monitor
> feat: add redis metric server monitor

- addons-cluster/redis/templates/_helpers.tpl
- addons-cluster/redis/values.yaml
> chore: add redis podAntiAffinity

- addons/redis/templates/_helpers.tpl
- addons/redis/templates/cmpd-redis-cluster.yaml
- addons/redis/templates/cmpv-redis-cluster.yaml
- addons/redis/templates/cmpv-redis-sentinel.yaml
- addons/redis/templates/cmpv-redis.yaml
- addons/redis/templates/paramsdef-redis-cluster.yaml
- addons/redis/templates/paramsdef-redis.yaml
- addons/redis/values.yaml
- Update registry fallback hierarchy to use main image registry as primary fallback
> chore: improve image registry fallback logic

- addons/tidb/config/pd-config-constraint.cue
- addons/tidb/config/tidb-config-constraint.cue
- addons/tidb/config/tikv-config-constraint.cue
fixes https://github.com/apecloud/apecloud/issues/11896
ref https://github.com/apecloud/apecloud-addons/pull/848
> fix: some incorrect type in tidb config constraints

- addons/postgresql/templates/backuppolicytemplate.yaml
fix: https://github.com/apecloud/apecloud/issues/12719
> chore: fix postgresql backup failed

- addons/postgresql/templates/configconstraint.yaml
* fix https://github.com/apecloud/kubeblocks-addons/issues/1842
> fix: pg cluster gets stuck in updating when using etcd as DCS

- addons/postgresql/scripts/pgbouncer-setup.sh
* fix https://github.com/apecloud/kubeblocks/issues/9645
> chore: do not run pgbouncer as root

- addons/postgresql/scripts/generate_patroni_yaml.py
* close: https://github.com/apecloud/kubeblocks/issues/9602
> chore: pg support synchronous mode

- addons/postgresql/scripts/generate_patroni_yaml.py
(cherry picked from commit 37b3148cca810ffa8017f9ad54af680c45753cb2)
> chore: pg support synchronous mode (#1941)

- addons/mongodb/dataprotection/shard-pbm-pre-backup.sh
- addons/mongodb/scripts/mongodb-shard-manage.sh
fix https://github.com/apecloud/apecloud/issues/12506
fix that post-provision jobs can't stop after the cluster stopped.
fix that e2e backup failed.
> fix: mongodb sharding backup failed

- addons/orioledb/config/pg16-config.tpl
fix https://github.com/apecloud/kubeblocks/issues/9676
> chore: fix orioledb restart crash

- addons/postgresql/scripts/generate_patroni_yaml.py
Reverts apecloud/kubeblocks-addons#1940
> Revert "fix: pg restore failed from wal-g"

- addons/postgresql/dataprotection/common-scripts.sh
- addons/postgresql/dataprotection/wal-g-archive.sh
- addons/postgresql/scripts/postgres-pre-setup.sh
- addons/postgresql/templates/_helpers.tpl
- addons/postgresql/templates/actionset-wal-g-incremental.yaml
- addons/postgresql/templates/actionset-wal-g-pitr.yaml
- addons/postgresql/templates/actionset-wal-g.yaml
- addons/postgresql/templates/cmpv.yaml
- addons/postgresql/values.yaml
```
│ 2025-09-04 13:26:12 INFO: start time of the oldest wal: 2025-09-04T12:51:05Z, end time of the latest wal: 2025-09-04T13:26:05Z, total size: 1073618961                                                                                                                                                                  │
│ 2025-09-04 13:26:17 INFO: check pg process is ok ...                                                                                                                                                                                                                                                                    │
│ 2025-09-04 13:26:17 INFO: start to upload missing ready WAL files... …
```
> fix: pg wal-g archive without time range

- addons/postgresql/dataprotection/common-scripts.sh
- addons/postgresql/dataprotection/wal-g-archive.sh
- addons/postgresql/scripts/init_container.sh
- addons/postgresql/templates/_helpers.tpl
- addons/postgresql/templates/actionset-wal-g-incremental.yaml
- addons/postgresql/templates/actionset-wal-g-pitr.yaml
- addons/postgresql/templates/actionset-wal-g.yaml
- addons/postgresql/templates/cmpv.yaml
- addons/postgresql/values.yaml
(cherry picked from commit ac092946d5d9605253162d5a43ea0188e88c281c)
> fix: pg wal-g archive without time range (#1969)

- addons/mongodb/dataprotection/common-scripts.sh
- addons/mongodb/dataprotection/shard-pbm-restore-prepare.sh
- addons/mongodb/scripts-ut-spec/replicaset_setup_spec.sh
- addons/mongodb/scripts/replicaset-setup.tpl
fix https://github.com/apecloud/kubeblocks/issues/9563
fix https://github.com/apecloud/kubeblocks/issues/9731
> fix: mongodb restore failed

- addons/mongodb/dataprotection/common-scripts.sh
- addons/mongodb/dataprotection/shard-pbm-restore-prepare.sh
- addons/mongodb/scripts/replicaset-setup.tpl
- addons/mongodb/templates/componentdefinition.yaml
pick https://github.com/apecloud/kubeblocks-addons/pull/1989
> chore: mongodb restore failed

- addons/clickhouse/dashboards/clickhouse.json
- addons/clickhouse/templates/_helpers.tpl
- addons/clickhouse/templates/actionset-incremental.yaml
- addons/clickhouse/templates/actionset.yaml
- addons/clickhouse/values.yaml
- addons/etcd/dashboards/etcd.json
- addons/redis/scripts-ut-spec/redis_cluster_server_start_spec.sh
ref: https://github.com/apecloud/apecloud/issues/13496
resolved https://github.com/apecloud/apecloud/issues/13576
> fix: ck & etcd dashboards

- addons-cluster/etcd/templates/_helpers.tpl
- addons-cluster/etcd/templates/cluster.yaml
- addons-cluster/etcd/values.yaml
> feat: Add support etcd podAntiAffinity

- .gitignore
- addons-cluster/loki/templates/cluster.yaml
- addons-cluster/loki/values.yaml
fixes https://github.com/apecloud/kubeblocks/issues/9762
> fix: set pvc for loki-write

- .github/workflows/update-release-notes.yml
ref: https://github.com/apecloud/apecloud-cd/pull/631/files
> chore: add update-release-notes workflow

- addons-cluster/elasticsearch-cluster/values.yaml
- addons-cluster/mysql-cluster/values.yaml
- addons-cluster/nebula-cluster/values.yaml
- addons-cluster/qdrant-cluster/values.yaml
- addons-cluster/tdengine-cluster/values.yaml
KubeBlocks will create the sa if needed, cluster chat DO NOT do it.
> chore: remove rbacEnabled in cluster chart
