apecloud/kubeblocks-addons

addons/kafka/templates/_helpers.tpl
addons/pulsar/templates/_helpers.tpl

label 'app.kubernetes.io/name' is used in Anywhere.

chore: add name and instance labels to kafka and pulsar

---

addons/kafka/configs/kafka-server-constraint.cue
addons/kafka/scripts/kafka-server-setup.sh.tpl
addons/kafka/templates/clusterdefinition.yaml
addons/kafka/values.yaml

1. add new parameters: k8s.nodeport
2. render configuration on the pod
```
$ k get svc kafka-broker-nodeport
NAME                    TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kafka-broker-nodeport   NodePort   10.124.6.254   <none>        9092:30603/TCP   10h
$ for i in `seq 3`;do kubectl exec -ti kafka-sparated-broker-$((i -1)) -c kafka -- sh -c "cat /opt/bitnami/kafka/config/kraft/server.properties |grep advertised.listeners" ;done
advertised.listeners=PLAINTEXT://10.128.0.26:30603
advertised.listeners=PLAINTEXT://10.128.0.81:30603
advertised.listeners=PLAINTEXT://10.128.0.33:30603
```

chore: access Kafka brokers from outside the k8s cluster (#5811)

---

addons/kafka/templates/clusterdefinition.yaml

fix: remove duplicate env in kafka

---

addons/kafka/templates/clusterdefinition.yaml

fix: convert integer env to string in kafka

---

addons/tidb-cluster/values.yaml

fix #33 , add resources for a basic cluster.

fix(tidb): add default resources for tidb-cluster

---

addons/apecloud-mysql/config/mysql8-auditlog-config.tpl
addons/apecloud-mysql/config/mysql8-config-constraint.cue
addons/apecloud-mysql/scripts/setup.sh
addons/apecloud-mysql/templates/clusterversion-auditlog.yaml
addons/apecloud-mysql/templates/configmap.yaml
addons/apecloud-mysql/values.yaml

1. add new cv: support mysql auditlog plugin;
2. add auditlog related configuration;
3. release 0.7 branch: https://github.com/apecloud/kubeblocks/commit/c37142b820bf3b9ee8d221fa1c10393dab97a7cd
Example:
```
kbcli cluster create auditlog-my --cluster-definition=apecloud-mysql --cluster-version=ac-mysql-8.0.30-auditlog
```

chore: support aduitlog for apecloud-mysql addon (#44)

---

addons/mysql/templates/clusterdefinition.yaml

fix: mysql cannot be started in some Storage Classes due to the presence of the "lost+found" directory

fix: mysql cannot be started in some Storage Classes 

---

addons/oceanbase-cluster/templates/_helpers.tpl
addons/oceanbase-cluster/templates/cluster.yaml
addons/oceanbase-cluster/values.schema.json
addons/oceanbase-cluster/values.yaml
addons/oceanbase/scripts/bootstrap.sh
addons/oceanbase/scripts/entrypoint.sh
addons/oceanbase/templates/clusterdefinition.yaml
addons/oceanbase/templates/clusterversion.yaml

```bash
helm install oceanbase ./addons/oceanbase
helm install myob ./addons/oceanbase-cluster  --set hostNetwork=true
```
will,  by default,  create an oceanbase cluster (with a primary cluster and a secondary cluster, each of which has EXACTLY ONE replcia, and has primary tenant and standy tenant created by default)
Fixed errors on running OB using HostNetwork, and on IN-PLACE restart.
- when use HostNetwork, set `podSpec.dnsPolicy: ClusterFirstWithHostNet`
- mount working dir to a PV to make 
- update some typos and errors in scritps.
- refine in-place recovering strategy.
- update `values.schema.json`
```bash
helm install oceanbase ./addons/oceanbase
helm package addons/oceanbase-cluster
kbcli cluster register oceanbase --source /path/to/your/ob-cluster-version.tgz
```
then you can …

chore: refind ob with hostnetwork and host path SC to restart in-place

---

addons/oceanbase-cluster/values.schema.json

- to support `oceanbase`  embeded as `kbcli cluster create` subcommand

chore: fix OceanBase values.schema.json

---

addons/redis-cluster/templates/cluster.yaml
addons/redis-cluster/values.schema.json
addons/redis-cluster/values.yaml

- adjust redis cluster default setting:
1. mode: replication
2. sentinel: enabled (need replication mode)
3. node port service: disabled

fix: redis-cluster default config

---

addons/foxlake/templates/_helpers.tpl

fix https://github.com/apecloud/kubeblocks/issues/6310
ref: https://github.com/apecloud/foxlake/commit/beea37bcee6ca76811944a9a3b85ecfea1e41407#diff-f95ae90ce86491673de77d607a5f2a5c5c68a7bba750edb2d66f69778e319ce9

chore: fix foxlake access password is not correct

---

addons/apecloud-mysql/scripts/set_config_variables.sh

Fixed the problem that the vtgate setting environment variable script regular expression could not match '/', resulting in an unavailable path.

fix: fix apecloud-mysql parameter match path

---

addons/oceanbase/dataprotection/backup.sh
addons/postgresql/dataprotection/config-wal-g.sh
addons/postgresql/dataprotection/wal-g-backup.sh
addons/postgresql/dataprotection/wal-g-config.sh
addons/postgresql/dataprotection/wal-g-delete.sh
addons/postgresql/dataprotection/wal-g-restore.sh
addons/postgresql/templates/actionset-wal-g.yaml
addons/postgresql/templates/backuppolicytemplate.yaml

how to use:
1. config wal-g tools
`kbcli cluster backup <clusterName> --method config-wal-g`
wait this job to completed.
2.  enable archiving
```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
generateName: pg-cluster-reconfiguring-
spec:
clusterRef: <clusterName>
reconfigure:
componentName: postgresql
configurations:
- keys:
- key: postgresql.conf
parameters:
- key: archive_command
value: "'envdir /home/postgres/pgdata/wal-g/env /home/postgres/pgdata/wal-g/wal-g wal-push %p'"
- key: archive_timeout
value: "60s"
name: postgresql-configuration
type: Reconfiguring
```
3. backup 
`kbcli clutser backup <clusterName> --method wal-g`
4. how to cleanup the expired wal logs
when deleting the full backup, it will cleanup the outedated wal logs with this backup. but if no any …

feat: support wal-g to backup/restore pgsql

---

addons/apecloud-mysql/Chart.yaml
addons/apecloud-mysql/config/mysql-scale-vttablet-config-effect-scope.yaml
addons/apecloud-mysql/templates/configconstraint.yaml
addons/apecloud-mysql/values.yaml

1. set `reloadOptions=unixSignalTrigger` for vttablet and vtgate
2. make pool size parameters in vttablet to be dynamic

chore: Use 'unixSignalTrigger' to support parameter hot reload for wescale

---

addons/zookeeper/values.yaml

fix: https://github.com/apecloud/kubeblocks-addons/issues/227
The logs path of the bitnami zookeeper image is `/opt/bitnami/zookeeper/logs/`
```
kuebclt exec -it zkeeper-pfkpxz-zookeeper-0 --  bash
I have no name!@zkeeper-pfkpxz-zookeeper-0:/$ ls /opt/bitnami/zookeeper/logs
zookeeper_audit.log
```

chore: change zookeeper logConfig path

---

addons/postgresql/Chart.yaml
addons/postgresql/config/patroni-parameter.yaml
addons/postgresql/config/patroni-reload.tpl
addons/postgresql/config/patroni-yaml.tpl
addons/postgresql/scripts/generate_patroni_yaml.py
addons/postgresql/templates/configmap-12.yaml
addons/postgresql/templates/configmap-14.yaml
addons/postgresql/templates/patroni-reload.yaml

resolve https://github.com/apecloud/kubeblocks/issues/6486
* support configure patroni parameters:
- ttl
- loop_wait
- retry_timeouts
- maximum_lag_on_failover
https://patroni.readthedocs.io/en/latest/dynamic_configuration.html#dynamic-configuration
* set patroni parameters default value:
- set maximum_lag_on_failover from 32MB to 1MB
- set check_timeline to true
```
ttl: 30
loop_wait: 10
retry_timeout: 10
maximum_lag_on_failover: 1048576
max_timelines_history: 0
check_timeline: true
```
set `check_timeline` to true, avoid timeline conflict.
https://patroni.readthedocs.io/en/latest/replication_modes.html#asynchronous-mode-durability
Reference:
> By default, when running leader elections, Patroni does not take into account the current timeline of replicas, what in some cases could be …

feat: support configure patroni parameters

---

addons/apecloud-mysql/Chart.yaml
addons/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
addons/apecloud-mysql/config/mysql-scale-vtgate-config-effect-scope.yaml
addons/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
addons/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
addons/apecloud-mysql/config/mysql-scale-vttablet-config-effect-scope.yaml
addons/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
addons/apecloud-mysql/values.yaml

Add some params for wescale VTGate and VTTablet. 
The functions involved include `non-transactional DML`, `routing of read-only transaction` and` vttablet info display when SQL executing`.

chore: add params for some wescale features

---

addons/apecloud-mysql-cluster/templates/cluster.yaml

apecloud-mysql's componentdefinition not ready, rollback to old API.

fix: apecloud-mysql componentDef

---

addons/redis/templates/clusterdefinition.yaml

fix: redis proxy svc has a wrong port mapping

---

addons/kafka/scripts/kafka-exporter-setup.sh.tpl
addons/kafka/scripts/kafka-exporter-setup.tpl

Describe: After setting up an SSL connection on port 9092, the original monitoring components required a new communication port. The Kafka cluster had reserved an internal port 9094. Therefore, adjustments were made in the startup script of the exporter.
Test: Whether SSL is enabled or not, the Kafka cluster run correctly.

feat: support kafka exporter when tls is enabled

---

docker/Dockerfile-charts

fix https://github.com/apecloud/kubeblocks-addons/actions/runs/9758635750/job/26933605961

chore: fix release addon image error

---

addons-cluster/pulsar-cluster/templates/_helpers.tpl
addons-cluster/pulsar-cluster/templates/cluster.yaml
addons-cluster/pulsar-cluster/templates/tests/benchmark.yaml
addons-cluster/pulsar-cluster/values.yaml
addons/pulsar/config/bookies-env.tpl
addons/pulsar/config/bookies-recovery-env.tpl
addons/pulsar/config/broker-env.tpl
addons/pulsar/config/proxy-env.tpl
addons/pulsar/scripts/init-bookies.sh
addons/pulsar/scripts/init-proxy.sh
addons/pulsar/scripts/start-bookies.sh
addons/pulsar/scripts/start-broker.sh
addons/pulsar/templates/_helpers.tpl
addons/pulsar/templates/clusterdefinition-zookeeper.yaml
addons/pulsar/templates/clusterdefinition.yaml
addons/pulsar/templates/componentdef-bkrecovery.yaml
addons/pulsar/templates/componentdef-bookkeeper.yaml
addons/pulsar/templates/componentdef-broker.yaml
addons/pulsar/templates/componentdef-proxy.yaml
addons/pulsar/templates/componentdef-zookeeper.yaml
addons/pulsar/templates/componentversion-bkrecovery.yaml
addons/pulsar/templates/componentversion-bookkeeper.yaml
addons/pulsar/templates/componentversion-broker.yaml
addons/pulsar/templates/componentversion-proxy.yaml
addons/pulsar/templates/componentversion-zookeeper.yaml
addons/pulsar/values.yaml

what's changed
1. add topologies
Pulsar supports three different cluster topologies, with two defined in clusterDefinition and one defined manually as creating the cluster:
- pulsar-basic-cluster
Configured in the pulsar-cluster/values.yaml file
This cluster topology includes three components: broker, zookeeper and bookkeeper
- pulsar-enhanced-cluster
Configured in the pulsar-cluster/values.yaml file
This cluster topology includes five components: broker, zookeeper, bookkeeper, proxy and bkrecovery
- Unspecified topology (i.e. topology: nil)
In this case, you can individually configure the proxy.enabled and bkrecovery.enabled options
This cluster approach allows more flexible composition of the required components
With all three topologies, you can configure serviceRef of external …

feat: upgrade pulsar to 0.9 API

---

addons/kafka/templates/componentdef-broker.yaml
addons/kafka/templates/componentdef-combine.yaml
addons/kafka/templates/componentdef-controller.yaml
addons/kafka/templates/componentdef-exporter.yaml
addons/kafka/values.yaml

The `images.registry` keep consistent with other addons.

chore: improve kafka image registry

---

addons-cluster/zookeeper/templates/cluster.yaml
addons-cluster/zookeeper/values.yaml
addons/zookeeper/templates/backuppolicytemplate.yaml

When creating a Zookeeper cluster, the minimum storage value is set to 10Gi, but it's actually created with 4Gi.
fix cloud issue #5999

fix: set zookeeper volume size via kblib and change default storage size to 10Gi

---

addons/elasticsearch/configs/elasticsearch-7-log4j2.properties
addons/elasticsearch/configs/elasticsearch-8-log4j2.properties

Sending logs to stdout is helpful for debugging if the pod crashes immediately after starting.

chore: output logs to both file and stdout

---

addons/postgresql/dataprotection/postgresql-pitr-restore.sh
addons/postgresql/dataprotection/wal-g-restore.sh

- The problem is that in OpsRequest, the timestamp should be in RFC-3339 format. But PostgreSQL doesn't recognize RFC-3339 format. So we need to do a format conversion
- Fixed both in pg PITR restore & wal-g PITR restore
- Optimize the code style when saving multi-line to a file
Fix: #967

fix: postgresql pitr not work

---

addons/apecloud-mysql/templates/clusterdefinition.yaml
addons/postgresql/templates/componentdefinition-12.yaml
addons/postgresql/templates/componentdefinition-14.yaml
addons/postgresql/templates/componentdefinition-15.yaml
addons/postgresql/templates/componentdefinition-16.yaml
addons/pulsar/templates/componentdef-bkrecovery.yaml
addons/pulsar/templates/componentdef-bookkeeper.yaml
addons/pulsar/templates/componentdef-broker.yaml
addons/pulsar/templates/componentdef-proxy.yaml
addons/redis/templates/componentdefinition-redis-cluster.yaml

chore: pick apecloud mysql support rerender after vscale to release-0.9

---

.github/workflows/check-chart-push.yml
.github/workflows/shellspec-pr-review.yml
.github/workflows/shellspec-push.yml
.shellspec
Makefile
README.md
utils/get_shellspec_include_path.sh

resolve https://github.com/apecloud/kubeblocks-addons/issues/1001 https://github.com/apecloud/kubeblocks-addons/issues/1002

chore: add shellspec ci

---

addons/redis/config/redis7-config-constraint.cue
addons/redis/config/redis7-config-effect-scope.yaml
addons/redis/config/redis7-config.tpl
addons/redis/dataprotection/common-scripts.sh
addons/redis/dataprotection/pitr-backup.sh
addons/redis/dataprotection/pitr-restore.sh
addons/redis/templates/backupactionset.yaml
addons/redis/templates/backuppolicytemplate.yaml

We leverage the AOF backup feature from Redis version 7.0 onwards to implement Point-In-Time Recovery (PITR). By enabling the `aof-timestamp-enabled yes` and `aof-disable-auto-gc no` parameters, we activate AOF timestamp annotations while disabling the automatic cleanup of historical AOF files. A StatefulSet, which is continuously responsible for the ongoing backup process, manages and tracks the AOF files.
The continuous backup process works as follows:
1. Historical AOF files in the data directory are compressed, packaged, and pushed to the backup repository.
2. The latest AOF file is backed up to the repository directory and continuously updated. When Redis triggers AOF rewriting, the file is compressed and archived as described in step 1.
3. The backup files in the repository are …

feat: support redis(standalone replica) pitr

---

addons/redis/dataprotection/pitr-restore.sh
addons/redis/dataprotection/restore-keys.sh
addons/redis/dataprotection/switch-data-dir.sh
addons/redis/templates/backupactionset.yaml

We can apply the key restoration by
```bash
kbcli cluster restore --backup "backup_name" --restore-keys  "a*,b*"
```
"a*" and "b*" represent the patterns of keys we want to restore, and split by comma.
for the details of the key pattern, refer to [Redis/KEYS](https://redis.io/docs/latest/commands/keys/)
1. We inject the key patterns into the restore pod as the environment variable `DP_RESTORE_KEY_PATTERNS`.
2. Let the prepareData job pull full data to a different directory.
3. Then in the postReady job, we start a local redis instance based on the full data,  and [SCAN](https://redis.io/docs/latest/commands/scan/) keys
by pattern then [MIGRATE](https://redis.io/docs/latest/commands/migrate/) the selected keys to the target redis instance.

feat: redis-restore-by-keys

---

examples/polardbx/cluster.yaml

- to https://github.com/apecloud/kubeblocks-addons/issues/1121

chore: update polardb example with SchedulePolicy API exampels

---

addons/pulsar/scripts-ut-spec/init_broker_spec.sh
addons/pulsar/scripts/init-broker.sh
addons/pulsar/scripts/start-bookies.sh
addons/pulsar/templates/_helpers.tpl
addons/pulsar/templates/configconstraints.yaml

(cherry picked from commit 002fd9598d2cdc7e365c42bfe72ef13003bd4419)

chore: fix pulsar addon typo

---

addons-cluster/clickhouse/templates/_helpers.tpl
addons-cluster/clickhouse/templates/cluster.yaml
addons-cluster/clickhouse/values.yaml
addons/clickhouse/templates/_helpers.tpl
addons/clickhouse/templates/clusterdefinition.yaml
addons/clickhouse/templates/cmpd-ch-keeper.yaml
addons/clickhouse/templates/cmpd-clickhouse.yaml
addons/clickhouse/templates/cmpv.yaml
addons/clickhouse/templates/configmap.yaml
addons/clickhouse/values.yaml
examples/clickhouse/cluster.yaml
examples/clickhouse/restart.yaml
examples/clickhouse/verticalscale.yaml
examples/clickhouse/volumeexpand.yaml

[#8403](https://github.com/apecloud/kubeblocks/issues/8403)

chore: fix keeper cmpd name in cluster

---

addons/redis/dataprotection/pitr-backup.sh

Resolves https://github.com/apecloud/kubeblocks-addons/issues/1172
Apply the same backup frequency and strategy to the `users.acl` as used for AOF file.

fix: update user.acl backup frequency in Redis PITR

---

addons-cluster/pulsar/templates/_helpers.tpl
addons-cluster/pulsar/templates/cluster.yaml
addons-cluster/pulsar/values.schema.json
addons-cluster/pulsar/values.yaml
addons/pulsar/config/2.11.2/bookies-config.tpl
addons/pulsar/config/3.0.2/bookies-config.tpl
addons/pulsar/config/bookies-recovery-env.tpl
addons/pulsar/templates/_helpers.tpl
addons/pulsar/templates/cmpv-bkrecovery.yaml
addons/pulsar/templates/cmpv-bookkeeper.yaml
addons/pulsar/templates/cmpv-broker.yaml
addons/pulsar/templates/cmpv-proxy.yaml
addons/pulsar/templates/cmpv-zookeeper.yaml
addons/pulsar/templates/configconstraints.yaml

- fix: https://github.com/apecloud/kubeblocks/issues/8467
1. set ServerVersion
2. add values.schema.json
3. update binary from `/bin/pulsar-admin` to `/pulsar/bin/pulsar-admin` in config-manager
4. update CMPVs,  cmpds,  pulsar 2 and pulsar 3, are incompatibile
5. create ZK service for both pulsar2 and pulsar3
6. remove `componenDefRef` in tpl.

fix: update pulsar cmpv and cc

---

addons/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
addons/apecloud-mysql/config/mysql8-config.tpl
addons/apecloud-postgresql/config/pg14-config.tpl
addons/clickhouse/configs/00_default_overrides.xml.tpl
addons/clickhouse/configs/ch_keeper_00_default_overrides.xml.tpl
addons/clickhouse/configs/client.xml.tpl
addons/etcd/config/etcd.conf.yaml.tpl
addons/orioledb/config/orioledb-config.tpl
addons/postgresql/config/pg12-config.tpl
addons/postgresql/config/pg14-config.tpl
addons/postgresql/config/pg15-config.tpl
addons/postgresql/config/pg16-config.tpl
addons/vanilla-postgresql/config/pg12-config.tpl
addons/vanilla-postgresql/config/pg14-config.tpl
addons/vanilla-postgresql/config/pg15-config.tpl

resolve https://github.com/apecloud/kubeblocks/issues/8598

fix: TLS_ENABLED might not be defined

---

addons/etcd/templates/cmpd.yaml

- fix: https://github.com/apecloud/kubeblocks-addons/issues/1292
exporter sets containerName to 'ETCD', and the container named 'ETCD' will be skipped when creating cluster with 'disableExporter=true'

chore: remove exporter api from ETCD cmpd

---

addons/pulsar/templates/cmpv-bookkeeper.yaml
examples/pulsar/README.md

- fix: https://github.com/apecloud/kubeblocks/issues/8723

chore: pulsar scale-in failed

---

addons/pulsar/templates/clusterdefinition.yaml

change the pulsar topology component order

fix: [pulsar] the order of bkrecovery component is incorrectly

---

addons/zookeeper/config/zookeeper-config.tpl
addons/zookeeper/templates/cmpd.yaml

chore: replace java by nc for zookeeper probe

---

addons-cluster/zookeeper/templates/cluster.yaml
addons/zookeeper/config/log4j.properties
addons/zookeeper/config/zookeeper-config.tpl
addons/zookeeper/templates/_helpers.tpl
addons/zookeeper/templates/cmpd.yaml

fix: zookeeper snapshot log mount error

---

addons/apecloud-mysql/templates/_helpers.tpl
addons/apecloud-postgresql/templates/_helpers.tpl
addons/etcd/templates/cmpd.yaml
addons/minio/templates/cmpd.yaml
addons/mogdb/templates/cmpd.yaml
addons/mongodb/templates/componentdefinition.yaml
addons/mysql/templates/_helpers.tpl
addons/orchestrator/templates/cmpd-raft.yaml
addons/polardbx/templates/cmpd-dn.yaml
addons/polardbx/templates/cmpd-gms.yaml
addons/postgresql/templates/componentdefinition-12.yaml
addons/postgresql/templates/componentdefinition-14.yaml
addons/postgresql/templates/componentdefinition-15.yaml
addons/postgresql/templates/componentdefinition-16.yaml
addons/redis/templates/cmpd-redis-7.yaml
addons/redis/templates/cmpd-redis-cluster-7.yaml
addons/tidb/templates/componentdefinition-pd.yaml
addons/vanilla-postgresql/templates/_helpers.tpl
addons/zookeeper/templates/cmpd.yaml

relates to https://github.com/apecloud/kubeblocks/pull/8416

chore: refactor roles

---

addons-cluster/kafka/templates/_helpers.tpl
addons-cluster/kafka/templates/cluster.yaml
addons-cluster/kafka/values.schema.json
addons-cluster/kafka/values.yaml
addons/kafka/templates/clusterdefinition.yaml
examples/kafka/cluster-combined.yaml

make kafka support headless svc/pod ip/nodeport network types

fix: make kafka support headless svc/pod ip/nodeport network types

---

addons-cluster/clickhouse-cluster/values.yaml
addons/clickhouse/configs/storage.xml.tpl
addons/clickhouse/dashboards/clickhouse.json
addons/clickhouse/templates/cmpd-ch.yaml
addons/clickhouse/templates/cmpd-keeper.yaml
addons/clickhouse/templates/configmap.yaml
examples/clickhouse/README.md

changed:
- storage configuration: User can override default storage policy or create different storage policy in xml configuration, if need to use different storage policy, need to bypass policy name when creating tables.
- fix hscale
- disable sharding

chore: clickhouse add storage configuration, fix hscale and disable sharding for 0.9

---

addons/apecloud-postgresql/templates/_helpers.tpl
addons/apecloud-postgresql/values.yaml

* fix https://github.com/apecloud/kubeblocks/issues/8939

fix: apepg create panic

---

.github/workflows/cherry-pick-auto.yml
.github/workflows/cherry-pick-label-check.yml
.github/workflows/cherry-pick-usage.yml
.github/workflows/cherry-pick.yml

**Auto Cherry-pick Instructions**
```
Usage:
- /nopick: Not auto cherry-pick when PR merged.
- /pick: Auto cherry-pick to all default branches when PR merged (release-0.9).
- /pick: release-x.x [release-x.x]: Auto cherry-pick to the specified branch when PR merged.
Example:
- /nopick
- /pick
- /pick release-0.9
```

chore: add auto cherry-pick workflow

---

addons/orioledb/templates/cmpv.yaml

fix https://github.com/apecloud/kubeblocks/issues/9048

chore: fix no matched image found for container init-syncer

---

addons/zookeeper/config/zookeeper-config.tpl
addons/zookeeper/config/zookeeper-params_schema.cue

* fix https://github.com/apecloud/apecloud/issues/10466

fix: add minSessionTimeout for zookeeper

---

addons/apecloud-postgresql/README.md
addons/clickhouse/README.md
addons/mongodb/README.md
addons/mysql/README.md
addons/postgresql/README.md
addons/victoria-metrics/README.md
addons/zookeeper/README.md
examples/apecloud-mysql/switchover-specified-instance.yaml
examples/apecloud-mysql/switchover.yaml
examples/apecloud-postgresql/switchover.yaml
examples/etcd/switchover.yaml
examples/mongodb/switchover-specified-instance.yaml
examples/mongodb/switchover.yaml
examples/mysql/README.md
examples/mysql/switchover-specified-instance.yaml
examples/mysql/switchover.yaml
examples/postgresql/switchover-specified-instance.yaml
examples/postgresql/switchover.yaml
examples/redis/switchover-specified-instance.yaml
examples/redis/switchover.yaml
examples/vanilla-postgresql/switchover-specified-instance.yaml
examples/vanilla-postgresql/switchover.yaml

```
kubectl explain OpsRequest.spec.switchover    
GROUP:      operations.kubeblocks.io
KIND:       OpsRequest
VERSION:    v1alpha1
FIELD: switchover <[]Object>
DESCRIPTION:
Lists Switchover objects, each specifying a Component to perform the
switchover operation.
FIELDS:
candidateName	<string>
If CandidateName is specified, the role will be transferred to this
instance.
The name must match one of the pods in the component.
Refer to ComponentDefinition's Swtichover lifecycle action for more details.
componentName	<string>
Specifies the name of the Component as defined in the cluster.spec.
componentObjectName	<string>
Specifies the name of the Component object.
instanceName	<string> -required-
Specifies the instance whose role will be transferred. A typical usage is to
transfer the leader …
```

chore: change switchover example

---

addons/apecloud-mysql/README.md
addons/etcd/README.md
addons/milvus/README.md
addons/vanilla-postgresql/README.md
examples/etcd/README.md

1. support auto extend addons readme with examples
2. fix etcd examples cluster-tls.yaml not found

chore: fix etcd examples cluster-tls.yaml not found

---

addons-cluster/victoria-metrics-cluster/templates/cluster.yaml
addons-cluster/victoria-metrics-cluster/values.yaml

kubeblocks v0.9 donnot support api 'restartOnFileChange', so this addon still need restart vminsert&vmselect by hand when vmstorage hscale

chore:add param for 0.9 victoria-metrics

---

addons/risingwave/templates/cmpd-connector.yaml

fix https://github.com/apecloud/kubeblocks/issues/9295

chore: fix create rw error container compute not found

---

addons-cluster/postgresql/templates/_helpers.tpl
addons/postgresql/README.md
addons/postgresql/templates/cmpd.yaml
examples/postgresql/README.md
examples/postgresql/cluster.yaml
examples/postgresql/restore.yaml

Use the existing label "workloads.kubeblocks.io/instance" as the scope label for PostgreSQL to avoid requiring users to explicitly specify the label when creating a cluster.

chore: chagne pg scope label

---

addons/postgresql/scripts/pgbouncer_setup.sh

* fix https://github.com/apecloud/kubeblocks/issues/9645

chore: do not run pgbouncer as root

---

addons/influxdb/values.yaml
addons/milvus/values.yaml
addons/mysql/values.yaml
addons/solr/values.yaml
addons/zookeeper/values.yaml

* Replace bitnami image repository with apecloud because of https://github.com/bitnami/charts/issues/35164

chore: replace bitnami repository with apecloud

---

addons-cluster/mongodb-cluster/Chart.yaml
addons-cluster/mysql-cluster/Chart.yaml
addons-cluster/postgresql-cluster/Chart.yaml
addons/mongodb/Chart.yaml
addons/mongodb/values.yaml
addons/mysql/Chart.yaml
addons/mysql/values.yaml
addons/postgresql/Chart.yaml
addons/postgresql/values.yaml

* bump wal-g verstion to 3.0.0 to fix failed to delete encrypted backup
* update the modified addon version and keep cluster chart version consistent with addon version

chore: fix failed to delete encrypted backup for KB09

---

addons/milvus/templates/clusterdefinition.yaml

This pull request makes a minor configuration update to the Milvus cluster definition. The only change is adjusting the `scrapePort` for the exporter from 9187 to 9091.

fix(milvus): Change milvus metrics scrapePort from 9187 to 9091

---

addons/mysql/templates/_helpers.tpl
addons/mysql/values.yaml

This pr https://github.com/apecloud/kubeblocks-addons/pull/2080 modify the container entrypoint command that will make the container restart if upgrade, so revert it and add a helm parameter to set the architecture.

chore: mysql support to set architecture
